float64 f1
float64 f2
float64 f3
float64 sp
float64 f1_speed
float64 f2_speed
float64 f3_speed
float64 sp_speed
float64 f1_torque
float64 f2_torque
float64 f3_torque
float64 sp_torque
---
bool result
