string[] name
float64[] q
float64[] v
float64[] t

int32 maxPressure
int32 hold

---
int32 error_code
int32[] torque_switch
int32[] pressure_stop
int32[] current_stop
int32 SUCCESSFUL = 0
int32 INVALID_DOF_NAME = -1
int32 INVALID_GOAL = -2
int32 CURRENT_LIMIT = -3
int32 PRESSURE_LIMIT = -4

---
Header header
string[] name
int32[] torque_switch
int32[] pressure_stop
int32[] current_stop
int32[] idle
